"""Add mapId to buildings

Revision ID: 11fb9adb22ac
Revises: 466d77c32eb5
Create Date: 2024-07-02 22:05:51.353474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11fb9adb22ac'
down_revision = '466d77c32eb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('building', schema=None) as batch_op:
        batch_op.add_column(sa.Column('map_id', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('building', schema=None) as batch_op:
        batch_op.drop_column('map_id')

    # ### end Alembic commands ###
