"""Add department_id to users

Revision ID: 4a6046672cce
Revises: 
Create Date: 2024-06-30 22:37:29.373322

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a6046672cce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('building', schema=None) as batch_op:
        batch_op.alter_column('latitude',
               existing_type=mysql.DECIMAL(precision=9, scale=6),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('longitude',
               existing_type=mysql.DECIMAL(precision=9, scale=6),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('image_path',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)

    with op.batch_alter_table('building_category', schema=None) as batch_op:
        batch_op.alter_column('categoryImage',
               existing_type=mysql.VARCHAR(length=300),
               nullable=False)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registrar', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('building_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('date_booked', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('event_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('event_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['registrar'], ['user_id'])
        batch_op.create_foreign_key(None, 'building', ['building_id'], ['building_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('duration')
        batch_op.drop_column('event_time')
        batch_op.drop_column('event_date')
        batch_op.drop_column('date_booked')
        batch_op.drop_column('building_id')
        batch_op.drop_column('registrar')

    with op.batch_alter_table('building_category', schema=None) as batch_op:
        batch_op.alter_column('categoryImage',
               existing_type=mysql.VARCHAR(length=300),
               nullable=True)

    with op.batch_alter_table('building', schema=None) as batch_op:
        batch_op.alter_column('image_path',
               existing_type=sa.String(length=500),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('longitude',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=9, scale=6),
               existing_nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=9, scale=6),
               existing_nullable=True)

    # ### end Alembic commands ###
